# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xtY8Fgpql5M5c2XUIlTJl6-TploHkM6W
"""

def oy_kunlari(belgi):
  if belgi=="Yanvar":
   return "31 kun"
  elif belgi=="Fevral":
   return "29 kun"
  elif belgi=="Mart":
   return "31 kun"
  elif belgi=="Aprel":
   return "30 kun"
  elif belgi=="May":
   return "31 kun"
  elif belgi=="Iyun":
   return "30 kun"
  elif belgi=="Iyul":
   return "31 kun"
  elif belgi=="Avgust":
   return "31 kun"
  elif belgi=="Sentyabr":
   return "30 kun"
  elif belgi=="Oktyabr":
   return "31 kun"
  elif belgi=="Noyabr":
   return "30 kun"
  elif belgi=="Dekabr":
   return "31 kun"
belgi=input("Oyni kiriting")
natija=oy_kunlari(belgi)
print(natija)